### ISSUE TITLE
The instructions no longer work for version 3.2.7 of Events Manager Pro :(

### ISSUE THREAD

**Issue by FrankEBailey** [Payfast/events-manager-pro-aggregation#1]
The instructions say

`In order to integrate EM Pro with PayFast you will need to include gateway.payfast.php on line 464 of events-manager-pro/add-ons/gateways/gateways.php as follows: include('gateway.payfast.php');`

Making the addition as above either before or after the content of line 464 doesn't make the Payfast gateway appear in the settings. Is it possible to get updated instructions that work for the most recent version (currently 3.2.7) of Events Manager Pro please?

![gateway](https://github.com/Payfast/mod-events-manager-pro/assets/273418/93dd6a36-384e-49df-b7cf-fe1e0213e4e4)

**Comment by fredjacobs** [comment]
Is this necessary when we deactivate legacy mode for Payment gateways? 
I see PayFast disappears then.

Do we need to upload these new files in the repo with latest version 3.2.7?

**Comment by bruce-atkinson** [comment]
@FrankEBailey, the instructions and code in [v1.0.1](https://github.com/Payfast/mod-events-manager-pro/releases/tag/v1.0.1) have now been updated for Events Manager v6.4.7.2 and Events Manager Pro v3.2.8.1.

@fredjacobs, you should not need use legacy mode with v1.0.1.
